### ISSUE TITLE
WriteLock confusion

### ISSUE THREAD

**Issue by KernelMaker** [malbrain/Btree-source-code#1]
Hi malbrain:
I have some confusions about the WriteLock in btree2u.c,  here is the code

`#define PHID 0x1           // writer phase (0/1)`
`#define PRES 0x2   // writer present`

`w = PRES | (tix & PHID);`
`r = __sync_fetch_and_add (lock->rin, w);` 

My confusion is that why you use two bits(PRES |(tix & PHID)) in writer,  what does the PHASE and PRESENT mean? It seems only one bit can work, because there is only one active writer at the most

Thanks^^

**Comment by malbrain** [comment]
Definition 1. A RW lock is phase-fair iff it has the following properties:

PF1 reader phases and writer phases alternate;
PF2 writers are subject to FIFO ordering, but only with regard to other writers;
PF3 at the start of each reader phase, all currently-unsatisfied read requests are satisfied (exactly one
write request is satisfied at the start of a writer phase); and
PF4 during a reader phase, newly-issued read requests are satisfied only if there are no unsatisfied write
requests pending.

The lock consists of four counters that keep track of the number of issued (rin, win) and completed (rout, wout) read and write requests (lines 1–3 of Listing 1). rin serves multiple purposes: for counting issued read requests, (PRES) is used to signal the presence of unsatisfied write requests and (PHID) is used to tell consecutive writer phases apart.

From: https://www.mpi-sws.org/~bbb/papers/pdf/rtsj11.pdf
