### ISSUE TITLE
Is LSM tree perform better than btree?

### ISSUE THREAD

**Issue by UncP** [malbrain/Btree-source-code#4]
I have just finished implementing concurrent btree, and now i am trying to optimize it, so is LSM tree perform better than btree?
<<The Log-Structured Merge-Tree>> by Patrick O'Neil, Edward Cheng. This is the paper that i should start with if i were to implement lsm tree?

**Comment by UncP** [comment]
The Log-Structured Merge-Tree

**Comment by funny-falcon** [comment]
It depends on load and implementation
Usually, LSM is better on write-heavy load, and BTree is better on read-only.
So, both algorithms are widely used and will never be surpassed by other.

**Comment by malbrain** [comment]
There is an experimental LSM btree implemented in threadskv10[gh].c
