### ISSUE TITLE
Why not lock the file in bt_mgr()?

### ISSUE THREAD

**Issue by UncP** [malbrain/Btree-source-code#5]
in threads2/threads2h.c, what if two progresses are creating btree manager with the same name at the same time? Shouldn't we lock the file?

**Comment by malbrain** [comment]
No, this is not a multi-process version -- it's multi-threaded only.  The bt_mgr open/create function is called only once, before any additional threads are created.  Each created thread is then given a pointer to the BtMgr object created by bt_mgr.

**Comment by UncP** [comment]
Is there any version that supports multi-processes in this repo?

**Comment by malbrain** [comment]
Here are the projects under btree-source-code:

btree2:	Single Threaded/MultiProcess versions that remove keys all the way back to an original empty btree, placing removed nodes on a free list. Operates under either memory mapping or file I/O. Recommended btrees hosted on network file systems.

threads2:	Multi-Threaded with latching implemented by a latch manager with test & set latches in the first few btree pages.

threadskv:	Multi-Threaded/Multi-Process based on threads2i.c that generalizes key/value storage in the btree pages. The page slots are reduced to 16 or 32 bits, and the value byte storage occurs along with the key storage.
