### ISSUE TITLE
bit of confused about 'volatile'?

### ISSUE THREAD

**Issue by UncP** [malbrain/Btree-source-code#6]
in threads2/**threads2h.c**

> typedef struct {
	BtLatch readwr[1];			// read/write page lock
	BtLatch access[1];			// Access Intent/Page delete
	BtLatch parent[1];			// Posting of fence key in parent
	BtSpinLatch busy[1];		// slot is being moved between chains
	volatile ushort next;		// next entry in hash table chain
	volatile ushort prev;		// prev entry in hash table chain
	volatile ushort pin;		// number of outstanding locks
	volatile ushort hash;		// hash slot entry is under
	volatile uid page_no;		// latch set page number
} BtLatchSet;

> typedef struct {
	uid  basepage;				// mapped base page number
	char *map;					// mapped memory pointer
	ushort slot;				// slot index in this array
	ushort pin;					// mapped page pin counter
	void *hashprev;				// previous pool entry for the same hash idx
	void *hashnext;				// next pool entry for the same hash idx
} BtPool;

i believe the above two structs has some similar features, one is for latchset, the other one is for page pool, they are both acquired using hash table, but there is no 'volatile' in BtPool, especially on key word 'hashprev' and 'hashnext', is it because when we pin BtPool, we only write lock the hash table slot, but when we pin BtLatchSet, we first read lock the hash table slot, if not found, then we impose the write on hash table slot?

**Comment by malbrain** [comment]
The bt_findpool function is called with the hash index entry in mgr->latch locked:,
so its pool variables don't need to be volatile.  However, you are right that the LatchSet variables don't need volatile, except for "pin" because access to them is always done under a read or write lock of the hash table entry, except when releasing a LatchSet at bt_unpinlatch.

    //  lock hash table chain
    hashidx = (uint)(page_no >> bt->mgr->seg_bits) % bt->mgr->seg_bits) % bt->mgr->hshsize;
    bt_spinwritelock (&bt->mgr->latch[hashidx]);
    //  look up in hash table
    if( pool = bt_findpool(bt, page_no, hashidx) ) {
    #ifdef unix
        __sync_fetch_and_or(&pool->pin, CLOCK_bit);
        __sync_fetch_and_add(&pool->pin, 1);
    #else
        _InterlockedOr16 (&pool->pin, CLOCK_bit);
        _InterlockedIncrement16 (&pool->pin);
    #endif
        bt_spinreleasewrite (&bt->mgr->latch[hashidx]);
        return pool;
    }
