### ISSUE TITLE
confused about atomic operation?

### ISSUE THREAD

**Issue by UncP** [malbrain/Btree-source-code#7]
in threadskv/**threads7.c**

you add atomic operation to btree, basically we acquire a lock using each key's hash value, then we conduct the normal insert routine, why this would make operation atomic and what's the use of this atomic operation?

**Comment by malbrain** [comment]
Besides the rwLock functions, the only atomic operations occur on latchvictim, latchdeployed, and pin, because their modifications occur outside the protection of the hash entry latch.

**Comment by UncP** [comment]
Sorry, i don't quite follow, can you explain it more specifically?

**Comment by malbrain** [comment]
The hash index lock is very temporary.  It serializes access for assignment of the available buffer pool slots, or the available latchSet entries.  To insert of a new key into an index page, a buffer pool slot, and in some btree-source-code versions a latchSet, has to be obtained for the operation to insert a new key to use to find the page and do the insert.  The latchSets contain the page locks, as assigned from the hash table by page_no.

**Comment by UncP** [comment]
1. we obtain lock for each key
2. we find each unique key in btree and this **make sure buffer pool and latchset are ready so no latchset will be obtained by using a victim nor buffer pool be evicted when we later do insert**.
3. we conduct insert routine
4. we release lock
is this the correct steps?

and what if we have two same key in one batch, what will happen when we try to acquire lock before the finding? it seems that it will be deadlock because we call this twice in 
**uint bt_setlock(BtDb *bt, BtKey *key)**
>   WriteLock (lock->readwr);


also what if we have too many key to insert atomic and there is not enough latchset or buffer pool? in this situation there must be some latchsets that will be victim or some buffer pool be evicted.
